
# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.3.1]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - name: Set environment variables
      run: |
        echo "Setting up Environment Variables"
        echo "${{ secrets.ENV_FILE }}" > .env
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - name: Archive production artifact
      uses: actions/upload-artifact@main
      with:
        name: out
        path: out
  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@main 
      - name: Download artifact
        uses: actions/download-artifact@main
        with:
          name: out
          path: out
      - name: Sync files to hosting
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server: explore-marinduque.refoldstudio.com
          username: deploy@explore-marinduque.refoldstudio.com
          password: ${{ secrets.ftp_password }}
          local-dir: ./out/
